import type { Metadata } from "next";
import { LegalLayout } from "@/components/marketing/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — STAGEGRID",
  description: "The terms governing your use of the STAGEGRID website and platform.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      updated="24 September 2026"
      intro="These Terms of Service govern your use of the STAGEGRID website, Event Builder, Equipment catalog and Portal. By using this site, you agree to these terms. Rental-specific terms are set out separately in our Rental Terms."
      sections={[
        {
          heading: "1. Acceptance of terms",
          paragraphs: [
            "By accessing or using this website you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use the website.",
          ],
        },
        {
          heading: "2. Use of the website",
          paragraphs: [
            "The Event Builder, Equipment catalog and Portal are provided to help you plan and configure event infrastructure. Estimates generated by these tools are indicative only, as described in each tool, and do not constitute a binding quote or contract.",
            "You agree not to misuse the website, attempt to gain unauthorised access to any system, or use the site for any unlawful purpose.",
          ],
        },
        {
          heading: "3. Quotes and bookings",
          paragraphs: [
            "A configuration created in the Event Builder or an equipment list added to the Basket does not constitute a confirmed booking. Bookings are only confirmed once a formal quote has been issued and accepted in writing by both parties.",
            "Pricing shown throughout the site is indicative and subject to change following technical review.",
          ],
        },
        {
          heading: "4. Intellectual property",
          paragraphs: [
            "All content, design, branding and software on this website is the property of STAGEGRID or its licensors and may not be reproduced without written permission.",
          ],
        },
        {
          heading: "5. Limitation of liability",
          paragraphs: [
            "STAGEGRID provides indicative estimates and planning tools in good faith but makes no warranty as to their completeness for any specific event. Final technical design and safety compliance require qualified engineering review as described in our Safety page.",
            "To the extent permitted by law, STAGEGRID is not liable for indirect or consequential loss arising from use of this website.",
          ],
        },
        {
          heading: "6. Governing law",
          paragraphs: [
            "These terms are governed by the laws of the Republic of South Africa.",
          ],
        },
        {
          heading: "7. Changes to these terms",
          paragraphs: [
            "We may update these Terms of Service from time to time. Continued use of the website after changes are posted constitutes acceptance of the revised terms.",
          ],
        },
      ]}
    />
  );
}
